trigger:
  branches:
    include:
      - main  # Trigger on the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Use the correct Python version
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Step 2: Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install Python Dependencies'

  # Step 3: Install Playwright Browsers
  - script: |
      playwright install
    displayName: 'Install Playwright Browsers'

  # Step 4: Install Allure Command Line Tool
  - script: |
      sudo apt-add-repository ppa:qameta/allure
      sudo apt-get update
      sudo apt-get install allure
    displayName: 'Install Allure'

  # Step 5: Run the Playwright Tests and Generate Allure Reports
  - script: |
      pytest --alluredir=./allure-results
    displayName: 'Run Playwright Tests with Allure'

  # Step 6: Generate the Allure Report
  - script: |
      allure generate ./allure-results --clean -o ./allure-report
    displayName: 'Generate Allure Report'

  # Step 7: Publish the Allure Report as an Artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/allure-report'
      artifact: 'AllureReport'
    displayName: 'Publish Allure Report Artifact'
