import os
import random

import spacy
from spacy.training import Example

# Increase the amount of training data
TRAIN_DATA = [

    # TRAINING DATA FOR OPEN COMMAND
    ("open https://www.google.com", {'entities': [(0, 4, 'COMMAND'), (5, 23, 'VALUE')]}),
    ("navigate to https://www.google.com", {'entities': [(0, 8, 'COMMAND'), (12, 30, 'VALUE')]}),
    ("launch https://www.google.com", {'entities': [(0, 6, 'COMMAND'), (7, 23, 'VALUE')]}),
    ("go to https://www.google.com", {'entities': [(0, 3, 'COMMAND'), (7, 23, 'VALUE')]}),
    ("open the website https://www.google.com", {'entities': [(0, 4, 'COMMAND'), (18, 30, 'VALUE')]}),
    ("navigate to the homepage https://www.google.com", {'entities': [(0, 8, 'COMMAND'), (23, 30, 'VALUE')]}),
    ("launch the app https://www.google.com", {'entities': [(0, 6, 'COMMAND'), (15, 30, 'VALUE')]}),
    ("go to the login page https://www.google.com", {'entities': [(0, 3, 'COMMAND'), (7, 27, 'VALUE')]}),
    ("open the search engine https://www.google.com", {'entities': [(0, 4, 'COMMAND'), (19, 30, 'VALUE')]}),
    ("navigate to the dashboard https://www.google.com", {'entities': [(0, 8, 'COMMAND'), (20, 30, 'VALUE')]}),

    # TRAINING DATA FOR TYPE COMMAND
    ("Enter 'code' into the first-name input", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 32, 'FIELD')]}),
    ("Enter 'code' into first-name input", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 28, 'FIELD')]}),
    ("Type 'code' into the username text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 29, 'FIELD')]}),
    ("Type 'code' into username text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 25, 'FIELD')]}),
    ("Type 'pass' into the firstname text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Type 'pass' into firstname text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Type 'hello' into the user-name input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Type 'hello' into user-name input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    ("Enter 'test' into the firstname input", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Enter 'test' into firstname input", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    (
        "Type 'user123' into the first-name input",
        {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 34, 'FIELD')]}),
    ("Type 'user123' into first-name input", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 30, 'FIELD')]}),
    ("Fill 'example' into the user-name input box",
     {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 33, 'FIELD')]}),
    ("Fill 'example' into user-name input box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Enter 'key' into the user-name input field",
     {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Enter 'key' into user-name input field", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Enter 'hello' into the email input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 28, 'FIELD')]}),
    ("Enter 'hello' into email input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 24, 'FIELD')]}),
    ("Type 'test' into the user_name text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Type 'test' into user_name text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Enter 'world' into the PIN input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 26, 'FIELD')]}),
    ("Enter 'world' into PIN input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 22, 'FIELD')]}),
    (
        "Enter 'key' into the first-name text box",
        {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 31, 'FIELD')]}),
    ("Enter 'key' into first-name text box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 27, 'FIELD')]}),
    ("Type 'user123' into the user_name text box",
     {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 33, 'FIELD')]}),
    ("Type 'user123' into user_name text box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Enter 'key' into the user-name input field",
     {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Enter 'key' into user-name input field", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Fill 'code' into the user-name input field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'code' into user-name input field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Enter 'input' into the password input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 31, 'FIELD')]}),
    ("Enter 'input' into password input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 27, 'FIELD')]}),
    ("Type 'test' into the password input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 29, 'FIELD')]}),
    ("Type 'test' into password input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 25, 'FIELD')]}),
    ("Fill 'data' into the firstname text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'data' into firstname text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Type 'pass' into the first-name box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 31, 'FIELD')]}),
    ("Type 'pass' into first-name box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 27, 'FIELD')]}),
    ("Type 'user123' into the firstname input box",
     {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 33, 'FIELD')]}),
    ("Type 'user123' into firstname input box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Fill 'code' into the user-name input field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'code' into user-name input field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Type 'example' into the firstname box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 33, 'FIELD')]}),
    ("Type 'example' into firstname box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Enter 'key' into the firstname text field",
     {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Enter 'key' into firstname text field", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Enter 'key' into the email box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 26, 'FIELD')]}),
    ("Enter 'key' into email box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 22, 'FIELD')]}),
    ("Fill 'user123' into the email text box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 29, 'FIELD')]}),
    ("Fill 'user123' into email text box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 25, 'FIELD')]}),
    ("Fill 'pass' into the user_name input field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'pass' into user_name input field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Enter 'key' into the PIN input field", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 24, 'FIELD')]}),
    ("Enter 'key' into PIN input field", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 20, 'FIELD')]}),
    ("Enter 'code' into the search input box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 28, 'FIELD')]}),
    ("Enter 'code' into search input box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 24, 'FIELD')]}),
    ("Enter 'code' into the search input", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 28, 'FIELD')]}),
    ("Enter 'code' into search input", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 24, 'FIELD')]}),
    ("Fill 'code' into the user-name text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'code' into user-name text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Fill 'pass' into the search box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 27, 'FIELD')]}),
    ("Fill 'pass' into search box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 23, 'FIELD')]}),
    ("Fill 'pass' into the search input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 27, 'FIELD')]}),
    ("Fill 'pass' into search input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 23, 'FIELD')]}),
    ("Enter 'code' into the email box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 27, 'FIELD')]}),
    ("Enter 'code' into email box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 23, 'FIELD')]}),
    ("Fill 'code' into the password text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 29, 'FIELD')]}),
    ("Fill 'code' into password text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 25, 'FIELD')]}),
    ("Enter 'input' into the firstname box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 32, 'FIELD')]}),
    ("Enter 'input' into firstname box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 28, 'FIELD')]}),
    ("Fill 'test' into the password box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 29, 'FIELD')]}),
    ("Fill 'test' into password box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 25, 'FIELD')]}),
    (
        "Fill 'test' into the username text field",
        {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 29, 'FIELD')]}),
    ("Fill 'test' into username text field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 25, 'FIELD')]}),
    ("Fill 'code' into the user-name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'code' into user-name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Fill 'user123' into the password text box",
     {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 32, 'FIELD')]}),
    ("Fill 'user123' into password text box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 28, 'FIELD')]}),
    ("Type 'test' into the password box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 29, 'FIELD')]}),
    ("Type 'test' into password box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 25, 'FIELD')]}),
    ("Type 'data' into the user_name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Type 'data' into user_name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Type 'world' into the firstname input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Type 'world' into firstname input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    ("Enter 'key' into the user_name box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Enter 'key' into user_name box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Fill 'key' into the user-name input box", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Fill 'key' into user-name input box", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (16, 25, 'FIELD')]}),
    ("Enter 'hello' into the user-name input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 32, 'FIELD')]}),
    ("Enter 'hello' into user-name input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 28, 'FIELD')]}),
    ("Fill 'hello' into the search text field", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 28, 'FIELD')]}),
    ("Fill 'hello' into search text field", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 24, 'FIELD')]}),
    ("Fill 'hello' into the search input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 28, 'FIELD')]}),
    ("Fill 'hello' into search input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 24, 'FIELD')]}),
    ("Type 'world' into the password text field",
     {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 30, 'FIELD')]}),
    ("Type 'world' into password text field", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 26, 'FIELD')]}),
    ("Enter 'code' into the username text box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 30, 'FIELD')]}),
    ("Enter 'code' into username text box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 26, 'FIELD')]}),
    ("Enter 'key' into the user_name text box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Enter 'key' into user_name text box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    (
        "Enter 'key' into the first_name text box",
        {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 31, 'FIELD')]}),
    ("Enter 'key' into first_name text box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 27, 'FIELD')]}),
    ("Type 'data' into the first-name text field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 31, 'FIELD')]}),
    ("Type 'data' into first-name text field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 27, 'FIELD')]}),
    ("Enter 'pass' into the firstname box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Enter 'pass' into firstname box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    ("Fill 'hello' into the PIN input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 25, 'FIELD')]}),
    ("Fill 'hello' into PIN input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 21, 'FIELD')]}),
    ("Fill 'data' into the email box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 26, 'FIELD')]}),
    ("Fill 'data' into email box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 22, 'FIELD')]}),
    ("Enter 'test' into the password box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 30, 'FIELD')]}),
    ("Enter 'test' into password box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 26, 'FIELD')]}),
    ("Type 'key' into the user-name input", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Type 'key' into user-name input", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (16, 25, 'FIELD')]}),
    ("Enter 'hello' into the email text box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 28, 'FIELD')]}),
    ("Enter 'hello' into email text box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 24, 'FIELD')]}),
    ("Fill 'pass' into the first_name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 31, 'FIELD')]}),
    ("Fill 'pass' into first_name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 27, 'FIELD')]}),
    ("Enter 'test' into the PIN input field", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 25, 'FIELD')]}),
    ("Enter 'test' into PIN input field", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 21, 'FIELD')]}),
    ("Type 'test' into the email input box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 26, 'FIELD')]}),
    ("Type 'test' into email input box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 22, 'FIELD')]}),
    ("Enter 'data' into the user-name text field",
     {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Enter 'data' into user-name text field", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    ("Enter 'world' into the user_name input field",
     {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 32, 'FIELD')]}),
    (
        "Enter 'world' into user_name input field",
        {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 28, 'FIELD')]}),
    ("Fill 'world' into the user-name input field",
     {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Fill 'world' into user-name input field", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    (
        "Enter 'key' into the user-name input box",
        {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Enter 'key' into user-name input box", {'entities': [(0, 5, 'COMMAND'), (7, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    (
        "Type 'hello' into the password input box",
        {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 30, 'FIELD')]}),
    ("Type 'hello' into password input box", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 26, 'FIELD')]}),
    ("Type 'example' into the username text field",
     {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 32, 'FIELD')]}),
    ("Type 'example' into username text field", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 28, 'FIELD')]}),
    ("Enter 'world' into the first_name text field",
     {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 33, 'FIELD')]}),
    (
        "Enter 'world' into first_name text field",
        {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 29, 'FIELD')]}),
    ("Fill 'pass' into the first_name text field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 31, 'FIELD')]}),
    ("Fill 'pass' into first_name text field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 27, 'FIELD')]}),
    ("Type 'key' into the user_name input", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Type 'key' into user_name input", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (16, 25, 'FIELD')]}),
    ("Fill 'world' into the first-name box", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 32, 'FIELD')]}),
    ("Fill 'world' into first-name box", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 28, 'FIELD')]}),
    ("Enter 'data' into the first_name input box",
     {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 32, 'FIELD')]}),
    ("Enter 'data' into first_name input box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 28, 'FIELD')]}),
    ("Enter 'data' into the username text field",
     {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 30, 'FIELD')]}),
    ("Enter 'data' into username text field", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 26, 'FIELD')]}),
    ("Fill 'data' into the password input box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 29, 'FIELD')]}),
    ("Fill 'data' into password input box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 25, 'FIELD')]}),
    ("Fill 'data' into the user_name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'data' into user_name input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Type 'key' into the search text field", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (20, 26, 'FIELD')]}),
    ("Type 'key' into search text field", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (16, 22, 'FIELD')]}),
    ("Type 'key' into the search input", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (20, 26, 'FIELD')]}),
    ("Type 'key' into search input", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (16, 22, 'FIELD')]}),
    ("Enter 'input' into the first-name box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 33, 'FIELD')]}),
    ("Enter 'input' into first-name box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 29, 'FIELD')]}),
    ("Type 'pass' into the firstname input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Type 'pass' into firstname input", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Enter 'user123' into the search input box",
     {'entities': [(0, 5, 'COMMAND'), (7, 14, 'VALUE'), (25, 31, 'FIELD')]}),
    ("Enter 'user123' into search input box", {'entities': [(0, 5, 'COMMAND'), (7, 14, 'VALUE'), (21, 27, 'FIELD')]}),
    ("Enter 'user123' into the search input", {'entities': [(0, 5, 'COMMAND'), (7, 14, 'VALUE'), (25, 31, 'FIELD')]}),
    ("Enter 'user123' into search input", {'entities': [(0, 5, 'COMMAND'), (7, 14, 'VALUE'), (21, 27, 'FIELD')]}),
    ("Fill 'code' into the user_name input field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'code' into user_name input field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Fill 'code' into the firstname text field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'code' into firstname text field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Enter 'input' into the first_name box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 33, 'FIELD')]}),
    ("Enter 'input' into first_name box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 29, 'FIELD')]}),
    ("Fill 'data' into the user-name text field",
     {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 30, 'FIELD')]}),
    ("Fill 'data' into user-name text field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 26, 'FIELD')]}),
    ("Fill 'example' into the user_name text field",
     {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 33, 'FIELD')]}),
    (
        "Fill 'example' into user_name text field",
        {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 29, 'FIELD')]}),
    ("Fill 'pass' into the email text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 26, 'FIELD')]}),
    ("Fill 'pass' into email text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 22, 'FIELD')]}),
    ("Enter 'input' into the first_name text box",
     {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 33, 'FIELD')]}),
    ("Enter 'input' into first_name text box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 29, 'FIELD')]}),
    ("Enter 'world' into the password text field",
     {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 31, 'FIELD')]}),
    ("Enter 'world' into password text field", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 27, 'FIELD')]}),
    ("Type 'example' into the first-name box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (24, 34, 'FIELD')]}),
    ("Type 'example' into first-name box", {'entities': [(0, 4, 'COMMAND'), (6, 13, 'VALUE'), (20, 30, 'FIELD')]}),
    ("Enter 'test' into the email input field", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 27, 'FIELD')]}),
    ("Enter 'test' into email input field", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 23, 'FIELD')]}),
    ("Enter 'input' into the user-name text field",
     {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 32, 'FIELD')]}),
    ("Enter 'input' into user-name text field", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 28, 'FIELD')]}),
    (
        "Enter 'test' into the firstname text box",
        {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Enter 'test' into firstname text box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    ("Enter 'hello' into the user-name box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 32, 'FIELD')]}),
    ("Enter 'hello' into user-name box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 28, 'FIELD')]}),
    ("Type 'input' into the firstname input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Type 'input' into firstname input", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    (
        "Enter 'data' into the password input box",
        {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 30, 'FIELD')]}),
    ("Enter 'data' into password input box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 26, 'FIELD')]}),
    ("Enter 'test' into the username box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (22, 30, 'FIELD')]}),
    ("Enter 'test' into username box", {'entities': [(0, 5, 'COMMAND'), (7, 11, 'VALUE'), (18, 26, 'FIELD')]}),
    ("Type 'world' into the firstname box", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Type 'world' into firstname box", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 27, 'FIELD')]}),
    ("Type 'pass' into the email box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 26, 'FIELD')]}),
    ("Type 'pass' into email box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 22, 'FIELD')]}),
    ("Type 'test' into the email input field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 26, 'FIELD')]}),
    ("Type 'test' into email input field", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 22, 'FIELD')]}),
    ("Enter 'input' into the first_name text box",
     {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 33, 'FIELD')]}),
    ("Enter 'input' into first_name text box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 29, 'FIELD')]}),
    ("Fill 'key' into the email text field", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (20, 25, 'FIELD')]}),
    ("Fill 'key' into email text field", {'entities': [(0, 4, 'COMMAND'), (6, 9, 'VALUE'), (16, 21, 'FIELD')]}),
    ("Enter 'world' into the search input box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 29, 'FIELD')]}),
    ("Enter 'world' into search input box", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 25, 'FIELD')]}),
    ("Enter 'world' into the search input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (23, 29, 'FIELD')]}),
    ("Enter 'world' into search input", {'entities': [(0, 5, 'COMMAND'), (7, 12, 'VALUE'), (19, 25, 'FIELD')]}),
    (
        "Type 'code' into the first-name text box",
        {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (21, 31, 'FIELD')]}),
    ("Type 'code' into first-name text box", {'entities': [(0, 4, 'COMMAND'), (6, 10, 'VALUE'), (17, 27, 'FIELD')]}),
    ("Fill 'world' into the user_name input box",
     {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (22, 31, 'FIELD')]}),
    ("Fill 'world' into user_name input box", {'entities': [(0, 4, 'COMMAND'), (6, 11, 'VALUE'), (18, 27, 'FIELD')]}),

    # TRAINING DATA FOR CLICK COMMAND
    ("clicks on the login_lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on login_lnk button", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the login_lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("click on the apply link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on apply link", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 19, 'TYPE')]}),
    ("click on the apply link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the submit link", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on submit link", {'entities': [(0, 5, 'COMMAND'), (9, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("click on the submit link", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on the lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the login-lnk button", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("click on login-lnk button", {'entities': [(0, 5, 'COMMAND'), (9, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on the login-lnk button", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on the register button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on register button", {'entities': [(0, 6, 'COMMAND'), (10, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("clicks on the register button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("click on the lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("click on lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 21, 'TYPE')]}),
    ("click on the lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on proceed button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the login link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on login link", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 19, 'TYPE')]}),
    ("click on the login link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("clicks on the login_lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on login_lnk button", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the login_lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on the lgn-btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on lgn-btn link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the lgn-btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on login-lnk link", {'entities': [(0, 5, 'COMMAND'), (9, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on the confirm button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on confirm button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the confirm button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the confirm button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on confirm button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the confirm button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("clicks on the proceed link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on proceed link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the proceed link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on the register button", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on register button", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("click on the register button", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the login_lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on login_lnk link", {'entities': [(0, 5, 'COMMAND'), (9, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the login_lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on proceed button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("clicks on the lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on the apply button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on apply button", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 21, 'TYPE')]}),
    ("click on the apply button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on register link", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on proceed button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the lgn-btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on the apply link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on apply link", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("clicks on the apply link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on the login button", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on login button", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 22, 'TYPE')]}),
    ("clicks on the login button", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("click on the confirm link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("click on confirm link", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 21, 'TYPE')]}),
    ("click on the confirm link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("click on the apply button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on apply button", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 21, 'TYPE')]}),
    ("click on the apply button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("clicks on the login link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on login link", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("clicks on the login link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on login-lnk button", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on register link", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the enter link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on enter link", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("clicks on the enter link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on the confirm button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on confirm button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the confirm button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("clicks on the submit button", {'entities': [(0, 6, 'COMMAND'), (14, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("clicks on submit button", {'entities': [(0, 6, 'COMMAND'), (10, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("clicks on the submit button", {'entities': [(0, 6, 'COMMAND'), (14, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the enter button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on enter button", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 21, 'TYPE')]}),
    ("click on the enter button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on the lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the lgn-btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on proceed button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("clicks on the lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the apply link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on apply link", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("clicks on the apply link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on login-lnk button", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on login-lnk button", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("click on the continue link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on continue link", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("click on the continue link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on the login link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on login link", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 19, 'TYPE')]}),
    ("click on the login link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on login-lnk button", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the login-lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on proceed button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on login-lnk link", {'entities': [(0, 5, 'COMMAND'), (9, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on register link", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the register link", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("clicks on register link", {'entities': [(0, 6, 'COMMAND'), (10, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("clicks on the register link", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on the submit link", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on submit link", {'entities': [(0, 5, 'COMMAND'), (9, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("click on the submit link", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on the continue link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on continue link", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("click on the continue link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on the login_lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on login_lnk button", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the login_lnk button", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 30, 'TYPE')]}),
    ("clicks on the confirm link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on confirm link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the confirm link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the submit link", {'entities': [(0, 6, 'COMMAND'), (14, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("clicks on submit link", {'entities': [(0, 6, 'COMMAND'), (10, 16, 'VALUE'), (17, 21, 'TYPE')]}),
    ("clicks on the submit link", {'entities': [(0, 6, 'COMMAND'), (14, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on proceed button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the proceed button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the login-lnk button", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("click on login-lnk button", {'entities': [(0, 5, 'COMMAND'), (9, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on the login-lnk button", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on proceed button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 23, 'TYPE')]}),
    ("click on the lgn_btn button", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 27, 'TYPE')]}),
    ("click on the apply link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on apply link", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 19, 'TYPE')]}),
    ("click on the apply link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the submit link", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on submit link", {'entities': [(0, 5, 'COMMAND'), (9, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("click on the submit link", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on the register button", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on register button", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("click on the register button", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the submit button", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("click on submit button", {'entities': [(0, 5, 'COMMAND'), (9, 15, 'VALUE'), (16, 22, 'TYPE')]}),
    ("click on the submit button", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the confirm button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on confirm button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the confirm button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on the continue button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on continue button", {'entities': [(0, 6, 'COMMAND'), (10, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("clicks on the continue button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on the lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on the confirm button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on confirm button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the confirm button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on the continue button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on continue button", {'entities': [(0, 6, 'COMMAND'), (10, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("clicks on the continue button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on the login-lnk link", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 28, 'TYPE')]}),
    ("clicks on login-lnk link", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on the login-lnk link", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 28, 'TYPE')]}),
    ("click on the enter link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on enter link", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 19, 'TYPE')]}),
    ("click on the enter link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on login-lnk link", {'entities': [(0, 5, 'COMMAND'), (9, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on proceed button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the proceed button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on register link", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the continue link", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("clicks on continue link", {'entities': [(0, 6, 'COMMAND'), (10, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("clicks on the continue link", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("clicks on the continue button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("clicks on continue button", {'entities': [(0, 6, 'COMMAND'), (10, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("clicks on the continue button", {'entities': [(0, 6, 'COMMAND'), (14, 22, 'VALUE'), (23, 29, 'TYPE')]}),
    ("click on the apply link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on apply link", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 19, 'TYPE')]}),
    ("click on the apply link", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("clicks on the confirm link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on confirm link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the confirm link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on register link", {'entities': [(0, 5, 'COMMAND'), (9, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("click on the register link", {'entities': [(0, 5, 'COMMAND'), (13, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("click on the login button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on login button", {'entities': [(0, 5, 'COMMAND'), (9, 14, 'VALUE'), (15, 21, 'TYPE')]}),
    ("click on the login button", {'entities': [(0, 5, 'COMMAND'), (13, 18, 'VALUE'), (19, 25, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("click on login-lnk link", {'entities': [(0, 5, 'COMMAND'), (9, 18, 'VALUE'), (19, 23, 'TYPE')]}),
    ("click on the login-lnk link", {'entities': [(0, 5, 'COMMAND'), (13, 22, 'VALUE'), (23, 27, 'TYPE')]}),
    ("clicks on the lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the lgn_btn link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the proceed link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on proceed link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the proceed link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the login-lnk link", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 28, 'TYPE')]}),
    ("clicks on login-lnk link", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on the login-lnk link", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 28, 'TYPE')]}),
    ("clicks on the apply link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on apply link", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("clicks on the apply link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on the apply button", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on apply button", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 22, 'TYPE')]}),
    ("clicks on the apply button", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the confirm link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on confirm link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the confirm link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the enter link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on enter link", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("clicks on the enter link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on the submit button", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("click on submit button", {'entities': [(0, 5, 'COMMAND'), (9, 15, 'VALUE'), (16, 22, 'TYPE')]}),
    ("click on the submit button", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("click on the lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("click on lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 21, 'TYPE')]}),
    ("click on the lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("click on the lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("click on lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (9, 16, 'VALUE'), (17, 21, 'TYPE')]}),
    ("click on the lgn-btn link", {'entities': [(0, 5, 'COMMAND'), (13, 20, 'VALUE'), (21, 25, 'TYPE')]}),
    ("clicks on the login link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on login link", {'entities': [(0, 6, 'COMMAND'), (10, 15, 'VALUE'), (16, 20, 'TYPE')]}),
    ("clicks on the login link", {'entities': [(0, 6, 'COMMAND'), (14, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("click on the submit button", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("click on submit button", {'entities': [(0, 5, 'COMMAND'), (9, 15, 'VALUE'), (16, 22, 'TYPE')]}),
    ("click on the submit button", {'entities': [(0, 5, 'COMMAND'), (13, 19, 'VALUE'), (20, 26, 'TYPE')]}),
    ("clicks on the proceed link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on proceed link", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 22, 'TYPE')]}),
    ("clicks on the proceed link", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 26, 'TYPE')]}),
    ("clicks on the lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (10, 17, 'VALUE'), (18, 24, 'TYPE')]}),
    ("clicks on the lgn_btn button", {'entities': [(0, 6, 'COMMAND'), (14, 21, 'VALUE'), (22, 28, 'TYPE')]}),
    ("clicks on the login-lnk link", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 28, 'TYPE')]}),
    ("clicks on login-lnk link", {'entities': [(0, 6, 'COMMAND'), (10, 19, 'VALUE'), (20, 24, 'TYPE')]}),
    ("clicks on the login-lnk link", {'entities': [(0, 6, 'COMMAND'), (14, 23, 'VALUE'), (24, 28, 'TYPE')]}),
]

# Load a blank English model

# Load a blank English model
current_script_path = os.path.dirname(os.path.abspath(__file__))  # Get the current script directory
project_root = os.path.join(current_script_path, '..', 'rift_model')  # Navigate to the parent and access 'rift'

nlp = spacy.blank('en')

# Add the Named Entity Recognizer to the pipeline
ner = nlp.add_pipe("ner")

# Add the custom entity labels to the NER
ner.add_label("COMMAND")
ner.add_label("VALUE")
ner.add_label("FIELD")
ner.add_label("TYPE")

# Prepare the training
optimizer = nlp.begin_training()

# Train the NER model for a few iterations
for i in range(20):
    random.shuffle(TRAIN_DATA)
    losses = {}
    for text, annotations in TRAIN_DATA:
        doc = nlp.make_doc(text)
        example = Example.from_dict(doc, annotations)
        nlp.update([example], losses=losses, drop=0.5)  # Update the model with the training data
    print(f"Iteration {i + 1}, Losses: {losses}")

# Save the trained model to disk
nlp.to_disk(project_root)
